language: node_js
branches:
  only:
    - master
node_js:
  - 11.9
services:
  - mysql
before_install:
  - mysql -e 'CREATE USER 'get5'@'localhost'; GRANT ALL PRIVILEGES ON *.* TO 'get5'@'localhost'; CREATE DATABASE get5test'
install:
  - yarn install
  - mv config/development.json.template config/development.json
  - sed -i -e 's/"user": "get5_user"/"user": "get5"/g' config/development.json
  - sed -i -e 's/"username": "get5_user"/"username": "get5"/g' config/development.json
  - sed -i -e 's/"dbKey": "Database 16 Byte Key."/"dbKey": "$DBKEY"/g' config/development.json

script:
  - yarn test