name: publish to ghcr
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  push:
    name: "g5api:latest"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set up QEMU
        uses: dbhi/qus/action@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository_owner }}
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}/g5api:latest
